% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\KOMAoption{captions}{tableheading}
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Multiple Imputation and Pattern-mixture Modeling to Assess the Sensitivity of Race/Ethnicity Effect Estimates Given Incomplete Data},
  pdfauthor={C. Clare Strange; Benjamin Stockton; Jordan Zvonkovich; Ofer Harel},
  pdfkeywords={pattern-mixture/shared parameter modeling, incomplete
data, racial/ethnic disparities, sentencing},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Multiple Imputation and Pattern-mixture Modeling to Assess the
Sensitivity of Race/Ethnicity Effect Estimates Given Incomplete Data}
\author{C. Clare Strange \and Benjamin Stockton \and Jordan
Zvonkovich \and Ofer Harel}
\date{2024-03-05}

\begin{document}
\maketitle
\begin{abstract}
Incomplete data are common in criminological research. The treatment of
incomplete data may alter effect estimates, including the observed
impacts of race/ethnicity on an outcome of interest. Knowing the degree
of certainty and robustness of effects is paramount importance
considering such research is often cited in policy discussions. We
assess the impacts of race/ethnicity on sentencing using data from
Pennsylvania's Court of Common Pleas (2010 -- 2019, N = ???). In doing
so, we present a novel strategy for sensitivity testing given incomplete
race/ethnicity data: multiple imputation in combination with
pattern-mixture models (PMMs). PMMs were developed for use with
incomplete data with non-ignorable missingness and are particularly
applicable to criminological research. Our results suggest that Black
offenders receive longer jail/prison sentences {[}Ben -- more detail
here?{]}, and that race/ethnicity effect estimates are relatively robust
against violations of the MAR assumption on the race or ethnicity of
offenders. We conclude that multiple imputation in combination with
pattern mixture models are a useful tool for criminologists to assess
the sensitivity of any effect of interest, and can be applied in any
criminological research context in which non-ignorable missingness is a
concern.
\end{abstract}
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[interior hidden, breakable, borderline west={3pt}{0pt}{shadecolor}, boxrule=0pt, frame hidden, sharp corners, enhanced]}{\end{tcolorbox}}\fi

\hypertarget{introduction-and-background}{%
\subsection{Introduction and
Background}\label{introduction-and-background}}

Criminal justice data are often ``incomplete,'' or have missing
observations. Incomplete data can stem from several, sometimes
interconnected sources, including (but not limited to) sample attrition
(e.g., observations exiting a study over time), selection (e.g., certain
individuals being more likely included in a study or an analysis), and
lapses in administrative data entry or recordkeeping (e.g., failure to
consistently record and report information). Regardless of the source,
the pattern of incomplete data will take one of several forms: missing
not at random (MNAR; otherwise known as nonignorable missingness),
missing at random (MAR), or missing completely at random (MCAR), which
has implications for the appropriate assumptions and method of treatment
(Rubin, 1987).

Discussed in depth elsewhere (see Stockton et al., 2023), administrative
criminal justice data have differing rates of completeness, with larger
ones tending to have higher rates (e.g., Federal or state-level
databases) than smaller, more localized ones. As demonstrated in a data
simulation by Stockton and colleagues (2023), the rate, pattern, and
treatment of incomplete data (even in moderate or small quantities) can
meaningfully alter effect estimates. Without appropriate treatment, the
analysis of incomplete data may lead to biased model estimates and
contribute to inaccurate conclusions about an effect of interest (Breen,
2015; Bushway et al., 2007).

The treatment of incomplete data and the robustness of effect estimates
are longstanding concerns of the criminological community. Brame \&
Paternoster (2003) noted over two decades ago the importance of these
concerns, which have since been addressed in various ways (see, e.g.,
the use of minimal assumptions and middle-ground estimators by Brame et
al.~2014). Despite these advancements, however, criminologists have
failed to consistently treat incomplete data and assess and report the
robustness of their findings (Stockton et al., 2023). The latter is
paramount for understanding the potential impact on effect estimates if
our assumptions about incomplete data do not hold.

Given the prevalence, inconsistent treatment, and potential impacts of
incomplete data on effect estimates, we argue that sensitivity testing
should be utilized to assess the robustness of an effect of interest in
any analysis of incomplete data with nonignorable missingness. In the
following sections, we briefly review the circumstances in which
incomplete criminal justice data are common and the methods by which
criminologists have treated incomplete data. We consider the potential
impacts of the treatment of incomplete data on research estimates, with
a substantive focus on the measurement of race/ethnicity effects as a
timely and relevant concern for criminologists, and in line with the
current analyses. We then review the limited ways in which
criminologists have assessed the sensitivity of race/ethnicity effects
given incomplete data and present a novel strategy: multiple imputation
(MI) with pattern-mixture modeling (PMM). We highlight that MI and PMM
can be used to assess the robustness of effects given incomplete data of
any assumed pattern (i.e., MAR, MNAR) and source (e.g., attrition,
selection), making it highly applicable and flexible to accommodate
common missingness issues faced by criminal justice researchers.

\hypertarget{common-sources-of-incomplete-data-in-criminological-research}{%
\subsubsection{Common Sources of Incomplete Data in Criminological
Research}\label{common-sources-of-incomplete-data-in-criminological-research}}

Criminal justice data may be incomplete for one or more unique
reasons---study attrition, sample selection, or inconsistent
administrative reporting and data entry practices are common examples.
Missingness due to study attrition may occur in a longitudinal data set
due to relocation, death, loss of contact, or disinterest in continuing.
Kim and Bushway (2018) provide an example of this in their examination
of the age-crime relationship using data from the National Longitudinal
Survey of Youth {[}NLSY{]}). They note the potential impacts of sample
attrition on their results if the observed dropout rates were more
prevalent among those with a higher probability of criminal involvement.
To assess this potential threat to validity they examined patterns of
missingness among the cohorts and found that, although their exploration
did indicate the possibility of selective sample attrition for those
with a higher risk of offending, these patterns differed by cohort and
did not present a clear indication that incomplete data biased their
results in a meaningful way.

Missingness due to selection may occur when individuals have a
differential likelihood of inclusion in a study or sample (Heckman,
1976). In policing research, only those individuals who have been
stopped by the police have the opportunity to be searched, arrested, or
to experience a use-of-force incident. In courts and sentencing
research, only individuals who make it through the stages of case
processing will receive a final disposition and corresponding sentence
length. Studies demonstrate that not all citizens are equally likely to
be stopped by the police or to complete all stages of case processing
(see Bowling \& Phillips, 2007; Kadane \& Lamberth, 2009; Kutateladze et
al., 2016; Pierson et al., 2020; TenEyck et al., 2024), therefore
policing and court data are poised to be incomplete with nonignorable
missingness due to sample selection. Gaebler and colleagues (2022)
provide a useful causal framework that expressly acknowledges that
prosecutorial charging decisions in part rely on people being stopped
and arrested in the first place (an area of racial/ethnic disparity),
note the importance of considering this from both a theoretical and
measurement perspective, and describe an estimand, the ``sateM'' (i.e.,
second-stage sample average treatment effect) that can be used to
measure discrimination in the second stage of a two-stage
decision-making process while accounting for potential discrimination in
the first stage.

Missingness due to inconsistent administrative reporting or data entry
may occur in studies using data sets that are compiled across multiple
independent agencies, such as that from the Uniform Crime Reports (UCR).
The UCR relies on the voluntary reporting of crime statistics by over
18,000 law enforcement agencies across the U.S. It is widely understood
that such data sets are incomplete as reporting practices are known to
vary between agencies and within agencies over time. There have been
multiple efforts to improve UCR data and address differential reporting,
including those of the National Archive of Criminal Justice Data
(NACJD), which involve imputation using county-level measures available
through their platform. DeLang and colleagues (2022) highlighted and
compared multiple methods of addressing differential reporting in the
UCR, including imputation using agencies' past reporting, multivariate
normal imputation (MVNI), and multiple imputation by chained equations
(MICE). They demonstrate that multiple imputation is the superior
approach because it reduces uncertainty in imputation and produces more
accurate standard errors.

\hypertarget{the-treatment-of-incomplete-sentencing-data-with-nonignorable-missingness}{%
\subsubsection{The Treatment of Incomplete Sentencing Data with
Nonignorable
Missingness}\label{the-treatment-of-incomplete-sentencing-data-with-nonignorable-missingness}}

Multiple imputation remains the ``gold standard'' treatment when MCAR or
MAR is the assumed missingness mechanism (Demuth \& Steffensmeier, 2004;
DeLang et al., 2022; Jordan \& Freiburger, 2010). We focus on the
treatment of incomplete sentencing data with nonignorable missingness
given its relevance to the current analyses.

Complete case analysis (CCA) is a common approach to analyzing
incomplete sentencing data (regardless of whether they are assumed
MCAR), particularly when the proportion of missing data is considered to
be small (see, e.g., Bales \& Piquero, 2012; Cassidy \& Rydberg, 2020;
Johnson et al., 2023; Kutateladze et al., 2014; Light, 2022; Ramos,
2023; Zane et al., 2022). It should be noted, however, that what
constitutes a ``small'' amount of missing data remains unclear (as noted
by Brame \& Paternoster, 2003). Missingness as low as five percent has
been shown to ``flip'' the direction of effect estimates even in the
context of a randomized controlled trial (RCT; Belin, 2009; Graham,
2009).

When data are incomplete due to sample selection (a form of nonignorable
missingness), scholars will often employ latent variable models to
reduce the degree of bias in estimation (e.g., the Heckman correction or
Tobit estimators, see Bärnighausen et al., 2011; Heckman, 1976; Johnson,
2014; Kutateladze et al., 2014; Saha et al., 1997; Stolzenberg et al.,
2013). Such models aim to explain the relationships between observed
variables (e.g., race and sentence length) by positing the existence of
unobserved (or latent) variables which are inferred from the data. Using
the two-stage Heckman correction in an analysis of sentence length as an
example, the first stage involves estimating the probability of
selection into the incarceration sample (the ``selection equation'') and
using the estimates from this model to calculate the inverse Mills (IM)
ratio. The second stage calls for the inclusion of the IM ratio as a
control variable to correct for selection bias in the outcome equation
modeling sentence length (Heckman, 1976). Importantly, Bushway and
colleagues (2007) illustrated that bias may remain a concern even in
studies in which the Heckman correction is employed. Many sentencing
scholars forego latent variable models altogether for justifiable
reasons (e.g., lacking appropriate selection criteria, problematic
collinearity between selection criteria and outcome variables), simply
noting the potential bias from sample selection as a limitation.

\hypertarget{the-potential-impacts-of-the-treatment-of-incomplete-data-on-raceethnicity-effect-estimates}{%
\subsubsection{The Potential Impacts of the Treatment of Incomplete Data
on Race/Ethnicity Effect
Estimates}\label{the-potential-impacts-of-the-treatment-of-incomplete-data-on-raceethnicity-effect-estimates}}

It has long been argued that the treatment of incomplete data may alter
estimates of the race/ethnicity effect on justice system outcomes (see
Baumer, 2013; Bushway et al, 2007; Kadane \& Lamberth 2009; Knox et al.,
2020; Stockton et al., 2023). We maintain this focus on race/ethnicity
as a timely and relevant concern given recent questions as to their
sustained presence and magnitude (see, e.g., Light, 2022). We define the
race/ethnicity effect as ``the differential treatment of people of
different races {[}and ethnicities{]} in the justice system who are
otherwise similarly situated with respect to legally relevant
characteristics'' (Stockton et al., 2023, p.2).

Discussed elsewhere at length (see Stockton et al., 2023), the magnitude
of race/ethnicity effects can vary greatly between studies and for
myriad reasons (e.g., contextual influences, bias and discrimination in
justice actor discretion, the differential impact of policy,
differential involvement in crime). Sentencing research has shown
race/ethnicity effect estimates varying from non-significant, to small,
moderate, or even large, and also often vary according to age, gender,
and type of case (see Doerner \& Demuth, 2010; Omori \& Petersen, 2020;
Ridgeway et al., 2020; Steffensmeier et al., 1998). While these
differences may be attributable, in part, to study contexts and
methodologies, Baumer (2013) notes that the true magnitude of
race/ethnicity effects on sentencing will remain uncertain so long as
sample selection bias is unaddressed in this literature. This sentiment
can be extended to bias from non-ignorable missingness from any source
(e.g., study attrition, reporting and data entry issues).

Within individual studies, the difference in race/ethnicity effect
estimates can be stark when comparing estimates prior to and after
treating bias due to nonignorable missingness. This was recently
illustrated by Knox and colleagues (2020) who initially reported that
around 10 percent of police uses-of-force against Black and Latino
individuals were discriminatory (before bias correction). After bias
correction, however, this estimate jumped to 39 percent. While this
example is specific to the policing literature, it is feasible that
untreated, nonignorable missingness in court and sentencing data could
introduce bias and contribute to inaccurate estimates of race/ethnicity
effects as well. For the sake of accurate prediction (to the greatest
extent possible given data limitations), it is essential to treat
nonignorable missingness and to assess the robustness of race/ethnicity
effects on sentencing.

From an applied standpoint, it is important to assess the robustness of
race/ethnicity effects because these estimates are often cited in
demographic impact statements that are used to justify significant
policy changes (The Sentencing Project, 2021). Many policymakers rely on
these statements to understand the potential consequences of a given
policy. For example, demographic or racial impact statements have been
used during the consideration of changes to statewide sentencing
policies in Minnesota (see Minnesota Sentencing Guidelines Commission,
2023), and mechanisms for creating racial impact statements have been
enabled by legislation in at least nine states (The Sentencing Project,
2021).

\hypertarget{assessing-the-sensitivity-of-raceethnicity-effects-given-incomplete-data}{%
\subsubsection{Assessing the Sensitivity of Race/Ethnicity Effects Given
Incomplete
Data}\label{assessing-the-sensitivity-of-raceethnicity-effects-given-incomplete-data}}

There are strong examples in which scholars have demonstrated methods to
assess the robustness of race/ethnicity effects in the presence of
incomplete data. Many of these examples extend from Manski's (2003) work
in econometrics, including the use of interval estimates (a range of
predicted outcome values in which the true value likely appears) and
bounds analysis, in which the goal is to identify the range of possible
outcome values under different model parameter assumptions. This work
has since been applied to the identification of treatment effects in
criminological research (see Manski \& Nagin, 2011)---a subject of study
in which random assignment is not always possible or ethical, and any
uncertainty in treatment effects need be explicit for policymakers to
gain a more nuanced understanding.

Brame et al.~(2014) built upon this work in proposing the use of a
minimal assumptions (MA) estimator. They note its utility particularly
in the social sciences in which the underlying mechanisms driving
outcomes may be complex and/or poorly understood. In their study of the
cumulative arrest prevalence between demographic groupings, the MA
estimator used by Brame and colleagues (2014) provided a lower bound
(assuming none of the individuals missing survey data were arrested) and
an upper bound (assuming all individuals missing survey data were
arrested) under the minimal assumptions that the survey responses were
accurate and the sample was representative. While this technique is
useful for considering maximum uncertainty (unlike MAR), the potentially
wide bounds can make it challenging to draw definitive conclusions about
an effect of interest. Recent research has employed algorithmic
strategies for bounding estimates, illustrating how effects estimated
under increasingly more minimal assumptions can gain credibility and
lose precision (Hamilton, 2023).

In their study of racial/ethnic discrimination in policing, Knox and
colleagues (2020) proposed the use of a Monte Carlo procedure to
construct confidence intervals that contain both the true lower and
upper bound endpoints with a specified probability (1 - α). They note,
however, that these procedures rely on relatively weak assumptions
(e.g., all use-of-force encounters with police are reported, race is
essentially randomly assigned in encounters, there is no racial
discrimination in the decision to stop civilians), which may be
plausible given the volume of policing research, but less likely to hold
in the examination of understudied topics. Stating assumptions
explicitly, as argued by Knox et al.~(2020) and others, is essential for
the consumers of research to properly evaluate the plausibility and
robustness of race/ethnicity effects.

\hypertarget{the-current-study}{%
\subsection{The Current Study}\label{the-current-study}}

The goal of the current study is to determine the impact of defendant
race/ethnicity on jail/prison sentence length, and to assess the
robustness of effect estimates given incomplete race/ethnicity data (a
common phenomenon in criminological data). In doing so we present
criminological scholars with a novel method for sensitivity testing:
multiple imputation and pattern-mixture modeling. This follows a recent
call to perform and report sensitivity testing in the analysis of
incomplete data, for which the missingness mechanisms can only be
assumed (Stockton et al., 2023).

Developed by Rubin (1974) and further since (see Little, 1993, Michiels
et al.~1999, Thomas et al., 2016), pattern-mixture models (PMMs) present
a flexible approach to sensitivity testing and can provide insights into
how the missingness is related to the observed data patterns. Instead of
assuming a single mechanism for missingness, PMMs allow for different
perturbations, or patterns, to be considered that are based on the
observed data.

In PMM, the selection patterns are explicitly modeled, and the analysis
is conducted separately for each pattern. This accounts for the fact
that different subgroups of individuals may have different reasons for
missing a value for race/ethnicity, and the parameters of interest
(here, the race/ethnicity effect estimate) can then be estimated by
combining information from all patterns. This somewhat reverses
traditional criminological thought about treating incomplete data; Put
simply, selection models (for example) model the outcome and then model
the selection (or non-ignorable missingness) given the outcome. On the
other hand, PMMs model the non-ignorable missingness and then model the
outcome given the non-ignorable missingness.

There are several advantages to using PMMs for sensitivity testing. They
are particularly useful when MCAR or MAR assumptions do not hold, they
do not require the use of exclusion variables or data from multiple
stages of case processing (which are often absent from administrative
data sets), and they can be used with multilevel models. For these
reasons (and others demonstrated below), we present MI and PMMs as an
advantageous method of assessing the robustness of race/ethnicity
effects in sentencing.

\hypertarget{data}{%
\subsubsection{Data}\label{data}}

We use the Pennsylvania Commission on Sentencing's (PCS) case-level
sentencing data for individuals convicted in a Court of Common Pleas
between January 1, 2010, and December 31, 2019 (N = FULL SAMPLE SIZE?).
The unit of analysis if the most serious sentence in a judicial
proceeding. We include all adult sentences (excluding homicide 1/2
cases, to which the sentencing guidelines in Pennsylvania do not
apply1).

\hypertarget{methods}{%
\subsubsection{Methods}\label{methods}}

We propose using multiple imputation and pattern-mixture models to
perform sensitivity analyses for the race effect estimates on the
jail/prison sentence length under incompleteness of the race variable.
We chose to use hurdle models with a lognormal generalized linear model
for the non-zero sentence lengths. Hurdle models can be used to model
complex data where the dependent variable is a combination of true zeros
and a continuous distribution for non-zero observations. Sentence length
is one such instance of this phenomena where offenders sentenced to jail
or prison time receive a sentence of \(Y > 0\) days (\(Y^* = Y/30\)
months) while offenders sentenced to a community sentence receive a
jail/prison sentence of \(Y = 0\) days (\(Y^* = 0\) months). Note the
distinction between sentence length which would be inclusive of
community and jail/prison sentence lengths, which are generally not
comparable, and our dependent variable, which is solely jail/prison
sentence length. When we refer to sentence length in this manuscript, we
are referring specifically to jail/prison sentence length.

Hurdle regression combines selection models that determine boundary
points of the dependent variable with an outcome model that determines
its nonbounded values. They treat these boundary values as observed
rather than censored, i.e., observations where the dependent variable is
equal to one of the boundary values are not the result of an inability
to observe the distribution above or below a certain point (Wooldridge,
2010). As defined by Mullahy (1986), ``the idea underlying the hurdle
formation is that a binomial probability model governs the binary
outcome of whether a count variate has a zero or a positive realization.
If the realization is positive, the `hurdle' is crossed, and the
conditional distribution of the positives is governed by a
truncated-at-zero count data model'' (p.345). The hurdle model we
consider treats the log of the number of days that an individual is
sentenced to incarceration as a positive continuous variable and first
model the zeros (i.e., individuals that do not receive incarceration
sentences). A benefit to hurdle models is that they can be used in a
multilevel context and are particularly appropriate when there is an
over-dispersed count distribution (both of which are common in
sentencing research) or when there's a mixture of a discrete variable
and continuous variable (Hester \& Hartman, 2017; Rydberg et al., 2018;
Thompson et al., 2020).

We are defining the race effect measured by the hurdle model as the
change in number of jail/prison days sentenced to between Black and
White offenders. This effect considers the zeros corresponding to
non-incarceration as true zeros, i.e.~the offenders are considered to
have served zero days in jail/prison.

The incomplete data analysis is performed in the multiple imputation
framework (Rubin, 1987). In this set-up the incomplete variables
sentence length, race, age, recommended minimum, and previous record are
imputed or filled in \(M\) times using draws from a predictive
distribution using a regression model. Less than 5\% of observations are
incomplete, with race being incomplete on 3\% of cases and the other
variables incomplete on less than 0.5\% of cases each.

The imputations are then used to create \(M\) completed data sets that
are then analyzed separately using a standard complete data method, in
this case a hurdle model. The estimates from each of the \(M\) model
fits are combined using Rubin's rules. In particular, we are going to
use random forests (Wright \& Ziegler, 2017) to perform the imputations
in the multiple imputation by chained equations framework (S. van Buuren
\& Groothuis-Oudshoorn, 2010; Raghunathan et al., 2001).

Pattern-mixture models can be used in conjunction with multiple
imputation to perform a sensitivity analysis for the model of interest
to particular perturbations of the distribution from which the
imputations are drawn (S. van Buuren, 2018, sec. 3.8). This allows us to
investigate the impacts nonignorable missingness could potentially have
on our analysis.

The pattern-mixture model approach allows the analyst to specify the
exact assumptions of the missingness model and assumptions of how the
distribution varies over different patterns. In our analysis, the two
patterns of interest are the offenders who have a reported race and
those who do not. It is plausible that these two groups have different
characteristics and that the latter group may not have a reported race
because of their true racial/ethnic identity (Stockton et al., 2023).
This is a form of what's known as non-ignorable missingness.

To assess the impacts of the non-ignorable missingness on the race
effects, we can use slight perturbations of the imputed race labels to
get a broader view of the range of potential estimates under different
distributional assumptions. Varying the distribution of imputations
based on the missing data pattern is what allows us to bring
pattern-mixture modeling into the fold.

\hypertarget{analysis}{%
\subsubsection{Analysis}\label{analysis}}

Our analysis begins with the multiple imputation step.\footnote{Code for
  analysis is available on GitHub at:
  \url{https://github.com/benjamin-stockton/crim-pattern-mixture} and
  data is available upon request.} We create \(M = 5\) completed data
sets using the chained equations framework under the default MAR
assumption. Then the sensitivity analysis perturbs the race/ethnicity
label to generate new imputations, followed by estimating the race
effects using the lognormal hurdle model.

\textbf{Dependent Variable}

The length of the jail/prison sentence modeled as a dependent variable
by our hurdle models. The length is measured in days and is zero for
offenders sentenced to a community sentence.

\textbf{Independent Variables}

The independent variables of interest are the offender's race and sex.
Race is coded as White, Black, Latino or Other. Sex is coded as male or
female.

\textbf{Legally Relevant Variables}

We also include legally relevant variables including the crime type,
whether the minimum sentence was recommended, if there was a trial or
plea, the offender's previous record, and the offense gravity score
(OGS). Additionally, the offender's age is included in the model. OGS
and age were centered and scaled before inclusion in the model.

\textbf{County-level Variable}

County-level random effects are included for both the lognormal model
for non-zero lengths, and the logistic model for the incarceration
decision. For each county, the average of the offense gravity score was
included to provide context for the typical cases in the county as well
as the proportion of cases that each county processes out of the total
number of cases processed in the state of Pennsylvania.

\hypertarget{tbl-descriptives}{}
\begin{longtable}[]{@{}lc@{}}
\caption{\label{tbl-descriptives}Descriptive statistics on subject
level.}\tabularnewline
\toprule\noalign{}
\textbf{Characteristic} & \textbf{N = 855,787} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Characteristic} & \textbf{N = 855,787} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Sentence Length (days) & \\
Mean (SD) & 163 (693) \\
(Range) & (0, 230,468) \\
(Missing) & 266 \\
Incarceration Decision & \\
0 & 464,301 (54\%) \\
1 & 391,220 (46\%) \\
(Missing) & 266 \\
OGS & \\
Mean (SD) & 3.41 (2.47) \\
(Range) & (1.00, 14.00) \\
OGS Squared & \\
Mean (SD) & 18 (27) \\
(Range) & (1, 196) \\
Recommended Minimum & \\
0 & 574,666 (67\%) \\
1 & 279,012 (33\%) \\
(Missing) & 2,109 \\
Trial & \\
0 & 837,609 (98\%) \\
1 & 18,178 (2.1\%) \\
Previous Record & \\
0 & 416,020 (49\%) \\
1/2/3 & 259,116 (30\%) \\
4/5 & 155,064 (18\%) \\
REVOC/RFEL & 25,584 (3.0\%) \\
(Missing) & 3 \\
Crime Type & \\
Drug & 195,303 (23\%) \\
DUI & 203,617 (24\%) \\
Other & 105,680 (12\%) \\
Persons & 133,637 (16\%) \\
Property & 217,550 (25\%) \\
Age & \\
Mean (SD) & 34 (11) \\
(Range) & (18, 100) \\
(Missing) & 1,662 \\
Age Squared & \\
Mean (SD) & 1,306 (910) \\
(Range) & (324, 9,940) \\
(Missing) & 1,662 \\
Sex & \\
Female & 194,068 (23\%) \\
Male & 661,719 (77\%) \\
Race/Ethnicity & \\
WHITE & 595,869 (72\%) \\
BLACK & 221,718 (27\%) \\
LATINO & 7,433 (0.9\%) \\
OTHER & 4,579 (0.6\%) \\
(Missing) & 26,188 \\
Year & \\
2010 & 88,527 (10\%) \\
2011 & 84,068 (9.8\%) \\
2012 & 86,638 (10\%) \\
2013 & 90,995 (11\%) \\
2014 & 89,307 (10\%) \\
2015 & 83,881 (9.8\%) \\
2016 & 81,538 (9.5\%) \\
2017 & 81,638 (9.5\%) \\
2018 & 82,504 (9.6\%) \\
2019 & 86,691 (10\%) \\
\end{longtable}

\hypertarget{tbl-county-descriptives}{}
\begin{longtable}[]{@{}lc@{}}
\caption{\label{tbl-county-descriptives}Descriptive statistics on county
level.}\tabularnewline
\toprule\noalign{}
\textbf{Characteristic} & \textbf{N = 855,787} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Characteristic} & \textbf{N = 855,787} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Average OGS by County & \\
Mean (SD) & 3.41 (0.73) \\
(Range) & (2.18, 6.20) \\
County Type & \\
Medium & 421,619 (49\%) \\
Rural & 286,644 (33\%) \\
Urban & 147,524 (17\%) \\
Number of Cases & \\
Mean (SD) & 34,709 (28,677) \\
(Range) & (344, 99,452) \\
Proportion of Cases & \\
Mean (SD) & 0.04 (0.03) \\
(Range) & (0.00, 0.12) \\
\end{longtable}

\hypertarget{results}{%
\subsection{Results}\label{results}}

\hypertarget{multiple-imputation}{%
\subsubsection{Multiple Imputation}\label{multiple-imputation}}

Prior to the multiple imputation, the offense gravity score (OGS),
offender age, and the square of both OGS and age are centered and
scaled. The imputations were generated using random forests in the
multiple imputation by chained equations algorithm. We used \(M = 5\)
since less than 5\% of all observations are missing (mainly on offender
race) (Graham et al., 2007). Random forests are a machine learning
method for modeling categorical and continuous outcomes (Breiman, 2001).

All variables included in the hurdle model are also included in the
imputation model; log of sentence length in days, offender race, sex,
age, previous record, offense gravity score, trial, minimum sentence
recommendation, year, and county.

\hypertarget{hurdle-models}{%
\subsubsection{Hurdle Models}\label{hurdle-models}}

A hurdle model models data with a high number of zeros (compared to
standard distributions). The model is composed of two components: the
hurdle for the zeros and the GLM for the non-zero part. Let
\(\pi_i = P(Y_i = 0)\) be the probability that the \(i\)th observation
is zero and \(P(Y_i \neq 0) = f_{y\neq 0}(y_i)\) where \(f_{y\neq 0}\)
is a truncated probability density function (Cragg, 1971). We are first
presenting the analysis of the data with multiple imputations under the
MAR assumption to demonstrate how the model fits the data and how to
interpret the race effect estimates.

\hypertarget{lognormal-glm-hurdle-model-with-predictors-on-hurdle-parameter}{%
\paragraph{Lognormal GLM Hurdle Model with Predictors on Hurdle
Parameter}\label{lognormal-glm-hurdle-model-with-predictors-on-hurdle-parameter}}

Under this first model, we will model the probability of \(Y_i = 0\) as
a logistic regression on the independent and legally relevant variables
with the R package \texttt{brms} (Bürkner, 2018).

\begin{equation}\protect\hypertarget{eq-hurdle-logistic}{}{
\mathrm{logit}^{-1}(P(Y_i = 0)) = \mathbf{x}_i \boldsymbol{\alpha} + \mathbf{z}_i \mathbf{v}.
}\label{eq-hurdle-logistic}\end{equation}

\begin{equation}\protect\hypertarget{eq-hurdle-glm}{}{
\log(Y_i) = \mathbf{x}_i \boldsymbol{\beta} + \mathbf{z}_i \mathbf{u} + \epsilon_i
}\label{eq-hurdle-glm}\end{equation} where \(\mathbf{v}\) and
\(\mathbf{u}\) are independent MVN with
\(E(\mathbf{v}) = E(\mathbf{u}) = 0\) and covariance matrices
\(Cov(\mathbf{v}) = G_v\) and \(Cov(\mathbf{u}) = G_u\),
\(\epsilon_i \overset{iid}{\sim} N(0, \sigma^2)\) and
\(\mathbf{v}, \mathbf{u}\) and \(\boldsymbol{\epsilon}\) are mutually
independent. \(\mathbf{x}_i\) and \(\mathbf{z}_i\) are rows from two
known design matrices for the population-level and group-level effects
respectively.

Here we include group-level effects for the year, the county, and the
crime-type in the county in case the judicial system sentences the
different crime-types differently relative to other counties. Each of
the population-level regression coefficients are given a
weakly-informative normal prior \(\beta_j \sim N(0, 100).\) The
group-level effects for the intercepts and effects for crime-type are
given noncentral t-distributions \(v_k \sim t_{3; 0, 2.5}\) and
\(u_k \sim t_{3; 0, 2.5}\) while the correlations between the
county-level slopes for proportion of cases and county-average OGS and
county-level intercepts are given \(\rho_{i.j} \sim lkj(1)\) priors. The
error term's variance also gets a noncentral t prior
\(\sigma \sim t_{3; 0, 2.5}.\) The coefficients \(\boldsymbol{\alpha}\)
are given normal priors \(\alpha_k \overset{iid}{\sim} N(0, 100).\)

Under this model we are assuming the incomplete data are MAR and the
missingness can be modeled entirely by the multiple imputation
procedure.

\hypertarget{tbl-brms-hurdle-model-summary-2-racesex}{}
\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tbl-brms-hurdle-model-summary-2-racesex}Fixed/population-level
effects for the non-zero part of the lognormal hurdle
model.}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Black & -0.09 & 0.01 & -0.12 & -0.07 \\
Latino & 0.03 & 0.05 & -0.07 & 0.13 \\
Other & 0.15 & 0.06 & 0.03 & 0.27 \\
Male \& Black & 0.07 & 0.01 & 0.05 & 0.09 \\
Male \& Latino & 0.13 & 0.05 & 0.03 & 0.23 \\
Male \& Other & -0.12 & 0.06 & -0.24 & 0.00 \\
\end{longtable}

\hypertarget{tbl-brms-hurdle-model-summary-2-zero-racesex}{}
\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tbl-brms-hurdle-model-summary-2-zero-racesex}Fixed/population-level
effects for the zero part of the lognormal hurdle model.}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Black & 0.03 & 0.01 & 0.01 & 0.06 \\
Latino & -0.29 & 0.08 & -0.44 & -0.13 \\
Other & -0.07 & 0.08 & -0.23 & 0.09 \\
Male \& Black & -0.31 & 0.02 & -0.34 & -0.28 \\
Male \& Latino & -0.39 & 0.08 & -0.56 & -0.22 \\
Male \& Other & -0.08 & 0.09 & -0.26 & 0.09 \\
\end{longtable}

The standard deviation parameter \(\sigma\) of the lognormal
distribution has a posterior mean of 1.04 (95\% CI: {[}1.04, 1.05{]}).

The county-level random/group-level effects and year-level
random/group-level effects are reported in Table~\ref{tbl-brms2-re}.

\hypertarget{tbl-brms2-re}{}
\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tbl-brms2-re}Random/group-level effect standard
deviation estimates for the lognormal hurdle model.}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
sd(Intercept) & 0.20 & 0.02 & 0.17 & 0.24 \\
sd(Hurdle Intercept) & 0.66 & 0.06 & 0.56 & 0.79 \\
\end{longtable}

In Figure~\ref{fig-cond-eff-brm2-racesex}, we can visualize the impacts
of race and sex on the sentence length in aggregate (including
zero-length sentences) (Figure~\ref{fig-cond-eff-brm2-racesex-1}) and on
the incarceration decision (Figure~\ref{fig-cond-eff-brm2-racesex-2}).
Numeric estimates are reported in Table~\ref{tbl-race-sex-effects}.
Under this model and the MAR missingness assumption, we find that there
is no significant difference in the sentence lengths between the
different racial groups within each sex. There is overlap between all
four credible intervals for both male offenders and female offenders.
Between the sexes, we do see significant differences. Female offenders
receive shorter sentences and are more likely to receive community
sentences regardless of race. There is a large amount of uncertainty in
the effect estimate for Latino offenders. The Other group also has a
relatively high amount of uncertainty and the male Other race offenders'
CI overlaps with all three other groups' CIs for both sexes, although
the mean posterior estimate is lower for sentence length.

\begin{figure}

\begin{minipage}[t]{0.47\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-racesex-1.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-racesex-1}Estimates on marginal
sentence length (includes zeros).}
\end{minipage}%
%
\begin{minipage}[t]{0.06\linewidth}

{\centering 

~

}

\end{minipage}%
%
\begin{minipage}[t]{0.47\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-racesex-2.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-racesex-2}Estimates on probability
of incarceration from the logistic regression on the zero-part of the
lognormal hurdle model.}
\end{minipage}%

\caption{\label{fig-cond-eff-brm2-racesex}Posterior estimates of the
interaction between race and sex effects on the sentence length in
days.}

\end{figure}

Results for the other terms in the model are reported in the Appendix.

\hypertarget{tbl-race-sex-effects}{}
\begin{longtable}[]{@{}llrrrr@{}}
\caption{\label{tbl-race-sex-effects}Estimates for sentence length
combining the non-zero and zero predictions for the eight combinations
of race and sex.}\tabularnewline
\toprule\noalign{}
Sex & Offender Race & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Sex & Offender Race & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Female & White & 17.31 & 1.15 & 15.25 & 19.74 \\
Female & Black & 15.39 & 1.06 & 13.44 & 17.57 \\
Female & Latino & 22.21 & 2.21 & 18.33 & 26.81 \\
Female & Other & 21.33 & 2.30 & 17.18 & 26.35 \\
Male & White & 25.83 & 1.61 & 22.92 & 29.17 \\
Male & Black & 30.39 & 1.80 & 27.23 & 34.10 \\
Male & Latino & 46.70 & 2.62 & 41.84 & 52.23 \\
Male & Other & 29.62 & 2.06 & 25.79 & 33.99 \\
\end{longtable}

\hypertarget{sensitivity-analysis-using-pattern-mixture-models}{%
\subsubsection{Sensitivity Analysis using Pattern-mixture
Models}\label{sensitivity-analysis-using-pattern-mixture-models}}

Evaluating the impacts of various nonignorable missingness mechanisms
can be accomplished with pattern-mixture models. The values of the
incomplete numeric data can be scaled or shifted. The same cannot be
done with categorical imputations, instead the proportion of each
category can be varied within the imputations compared to the observed
distribution or the MAR imputed distribution.

While there are very few missing sentence lengths, I could also modify
the imputed sentence lengths with a scale \(c\) or shift \(\delta\).
Scaling maintains that offenders that are non-incarcerated will remain
non-incarcerated while the sentences of incarcerated defenders would
shift. A positive shift would make all offenders incarcerated while a
negative shift would impose negative sentence lengths that would need to
be corrected to use Poisson or lognormal hurdle glms.

To perturb the imputations, we modify the vector of probabilities
\(\mathbf{p} = (p_1, p_2, p_3, p_4)'\) of class membership for each
racial/ethnic group under consideration (White, Black, Latino, or
Other). A vector of scale parameters
\(\mathbf{c} = (c_1, c_2, c_3, c_4)'\) is chosen such that the new
racial/ethnic group label will be drawn from the normalized vector
\(\mathbf{p}^* = \frac{1}{\sum_{j=1}^4 c_j p_j} (c_1 p_1, c_2 p_2, c_3 p_3, c_4 p_4)'\)
so that the probability vectors remains the same if \(c_j = 1\) for each
\(j = 1,\dots,4.\) For simplicity, we will focus on varying the
probability of assigning a White label by changing only \(c_1\) while
holding \(c_2 = c_3 = c_4 = 1.\)

The vector of probabilities \(\mathbf{p}_i\) is obtained for each
incomplete observation \(i\) by re-fitting the same random forest used
in the initial mulitple imputation step. This vector is then scaled and
normalized using the same scaling vector \(\mathbf{c}\) for all
incomplete observations. The probability vectors \(\mathbf{p}^*\) are
used to draw new imputed racial/ethnic group labels for the incomplete
observations. This procedure is repeated, including the model fitting,
across each of the \(M\) completed data sets resulting in a new set of
\(M\) completed data sets with modified imputations. The new set of
completed data sets is then analyzed as before using an lognormal hurdle
model. Estimates from each variation of \(\mathbf{c}\) that is chosen
are then compared graphically in Figure~\ref{fig-cond-eff}.

We choose to vary \(c_1\) along the sequence
\(\{0.1, 0.33, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2\}.\) When \(c_1 = 1\),
the imputations correspond to the original imputation model under the
MAR assumption. For \(c_1 < 1\), fewer observations are imputed with a
White label than under the MAR assumption reflecting a more diverse
population of offenders who have unknown or unreported race labels. The
opposite is true for \(c_1 > 1\), reflecting a more White population of
offenders. We include cases such as \(c_1 = 0.1\) and \(c_1 = 0.33\) as
well as \(c_1 = 1.5\) and \(c_1 = 2\) as rather implausible extreme
conditions to investigate what could happen in the most extreme
circumstances.

Figure~\ref{fig-cond-eff} displays the race effects on sentence length
for the White, Black, Latino, and Other racial/ethnic groups by sex
(female/male) including the zero-day non-incarceration sentences. In
general, we see that estimates for each ethnic group's expected
incarceration decision and sentence length tend to be very stable
regardless of how the imputation distribution of race is altered by
\(k\). This indicates that our estimate under the MAR assumption is
likely to be robust against violations of the MAR assumption on the race
or ethnicity of offenders.

Since the estimates are statistically indistinguishable (i.e.~the
credible intervals for each estimate overlap for all \(k\)), we will
take a closer look at the estimates under the MAR assumption where
\(k = 1\). The estimates under all \(k\) are displayed in
Table~\ref{tbl-cond-eff-f} and Table~\ref{tbl-cond-eff-m}. We find that
White female offenders are predicted to receive sentences of 17.3 days
with a 95\% credible interval of 15.3 to 19.7 days, Black female
offenders are predicted to receive sentences of 15.4 days (95\% CI of
(13.4, 17.6)), Latina female offenders are predicted to receive
sentences of 22.2 days (95\% CI of (18.3, 26.8)), and female offenders
of another race/ethnicity are predicted to receive sentences of 21.3
days (95\% CI of (17.2, 26.4)).

Male offenders receive longer sentences than female offenders of the
same race/ethnicity under all sensitivity levels \(k\). We predict White
male offenders to receive sentences of 25.8 days (95\% CI of (22.9,
29.2)), Black male offenders to receive sentences of 30.4 day s (95\% CI
of (27.2, 34.1)), Latino male offenders to receive sentences of 46.7
days (95\% CI of (41.8, 52.2)), and male offenders of another
race/ethnicity to receive a sentence of 29.6 days (95\% CI of (25.8,
34.0)).

\begin{figure}

{\centering \includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-1.pdf}

}

\caption{\label{fig-cond-eff}Estimated sentence lengths under each
sensitivity analysis setting for White, Black, Latino/a, and Other
race/ethincity offenders by Sex (female/male) including the zero-day
non-incarcerated sentences.}

\end{figure}

\begin{figure}

{\centering \includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-hu-1.pdf}

}

\caption{\label{fig-cond-eff-hu}Estimated probability of a zero-day
non-incarcerated sentence under each sensitivity analysis setting for
White, Black, Latino/a, and Other race/ethincity offenders by Sex
(female/male)}

\end{figure}

\begin{figure}

{\centering \includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-marginal-eff-1.pdf}

}

\caption{\label{fig-marginal-eff}Estimated marginal sentence lengths
under each sensitivity analysis setting for White, Black, Latino/a, and
Other race/ethincity offenders by Sex (female/male) excluding the
zero-day non-incarcerated sentences.}

\end{figure}

\hypertarget{tbl-cond-eff-f}{}
\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0394}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1024}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1339}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1024}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1339}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1102}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1417}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1024}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1339}}@{}}
\caption{\label{tbl-cond-eff-f}Estimated sentences lengths and posterior
standard errors for the various sensitivity analysis conditions for
White, Black, Latino/a, and Other race/ethnicity offenders for female
offenders.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
\(k\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
White Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(White Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Black Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Black Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Latina Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Latina Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Other Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Other Female)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
\(k\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
White Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(White Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Black Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Black Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Latina Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Latina Female)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Other Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Other Female)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0.33 & 17.19 & 1.11 & 15.28 & 0.99 & 22.26 & 2.16 & 21.51 & 2.39 \\
0.50 & 17.52 & 1.16 & 15.55 & 1.04 & 22.71 & 2.27 & 21.98 & 2.39 \\
0.75 & 17.46 & 1.16 & 15.48 & 1.05 & 22.58 & 2.13 & 21.78 & 2.35 \\
0.90 & 17.42 & 1.17 & 15.47 & 1.06 & 22.54 & 2.24 & 21.86 & 2.33 \\
1.00 & 17.31 & 1.15 & 15.39 & 1.06 & 22.21 & 2.21 & 21.33 & 2.30 \\
1.10 & 17.39 & 1.20 & 15.44 & 1.09 & 22.45 & 2.21 & 21.83 & 2.41 \\
1.25 & 17.63 & 1.14 & 15.65 & 1.04 & 22.74 & 2.20 & 22.17 & 2.37 \\
1.50 & 17.44 & 1.22 & 15.48 & 1.10 & 22.51 & 2.24 & 21.90 & 2.33 \\
2.00 & 17.40 & 1.22 & 15.43 & 1.08 & 22.60 & 2.09 & 21.80 & 2.46 \\
\end{longtable}

\hypertarget{tbl-cond-eff-m}{}
\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0442}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0973}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1327}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0973}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1327}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1239}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1416}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0973}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1327}}@{}}
\caption{\label{tbl-cond-eff-m}Estimated sentences lengths and posterior
standard errors for the various sensitivity analysis conditions for
White, Black, Latino/a, and Other race/ethnicity offenders for male
offenders.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
\(k\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
White Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(White Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Black Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Black Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Latino Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Latina Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Other Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Other Male)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
\(k\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
White Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(White Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Black Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Black Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Latino Female
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Latina Male)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Other Male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
se(Other Male)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0.33 & 25.64 & 1.52 & 30.22 & 1.67 & 46.33 & 2.51 & 29.79 & 1.94 \\
0.50 & 26.07 & 1.59 & 30.72 & 1.76 & 47.04 & 2.56 & 30.31 & 2.14 \\
0.75 & 26.00 & 1.62 & 30.62 & 1.79 & 46.90 & 2.60 & 30.16 & 2.12 \\
0.90 & 25.97 & 1.62 & 30.59 & 1.76 & 46.85 & 2.68 & 30.12 & 2.11 \\
1.00 & 25.83 & 1.61 & 30.39 & 1.80 & 46.70 & 2.62 & 29.62 & 2.06 \\
1.10 & 25.91 & 1.63 & 30.53 & 1.80 & 46.77 & 2.65 & 30.12 & 2.11 \\
1.25 & 26.23 & 1.60 & 30.87 & 1.74 & 47.21 & 2.62 & 30.52 & 2.08 \\
1.50 & 25.99 & 1.67 & 30.59 & 1.85 & 46.88 & 2.65 & 30.18 & 2.15 \\
2.00 & 25.91 & 1.68 & 30.52 & 1.85 & 46.74 & 2.67 & 30.14 & 2.06 \\
\end{longtable}

\hypertarget{discussionconclusion}{%
\subsection{Discussion/Conclusion}\label{discussionconclusion}}

Criminal justice data are often incomplete due to study attrition,
sample selection, data entry or reporting issues, and myriad other
reasons. Criminologists have inconsistently addressed incomplete data,
which may contribute to questions regarding the plausibility and
sensitivity of effect estimates. In particular, the presence and
magnitude of race/ethnicity effects in court contexts has drawn recent
attention. It is important that the field continue developing strategies
to assess the robustness of findings against violations of the
underlying assumptions of incomplete data (e.g., MAR). Specificity
regarding race/ethnicity effect estimates is of the utmost importance
given the potential policy impacts of research findings in this topic
area.

Building upon a body of work regarding sensitivity testing of
race/ethnicity effects, we demonstrate how MI and PMM can be used in
conjunction to assess the robustness of race/ethnicity effects given
incomplete data of any given pattern (i.e., MAR, MNAR) and source (e.g.,
attrition, selection). This approach is highly applicable to analyses of
criminal justice data, which often include nonignorable missingness and
questions about the robustness of effect estimates. We demonstrate that
race/ethnicity effects appear stable against violations of the MAR
assumption for missingness on the defendant race variable.

The current study has several limitations. First, we have not compared
PMMs to other methods of sensitivity analysis, we have simply argued its
theoretical utility and demonstrated its application. Future research
should compare the robustness of estimates under different methods of
sensitivity analysis. Second, reducing the sentencing decisions to a
binary incarcerated/not decisions in a study of punishment severity
risks losing information about the varying degrees of severity of
non-incarcerative sentences (Pina-Sanchez et al., 2020). Future research
should consider how these non-incarcerative sentencing options should be
quantified in terms of punitiveness and in comparison to incarceration
sentence lengths.

\hypertarget{acknowledgments}{%
\subsection{Acknowledgments}\label{acknowledgments}}

The authors would like to thank the Pennsylvania Commission on
Sentencing (PCS) for providing data. The points of view presented in
this paper are those of the authors and do not necessarily represent the
official position of PCS.

\newpage

\hypertarget{references}{%
\subsection*{References}\label{references}}
\addcontentsline{toc}{subsection}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-breiman2001}{}}%
Breiman, L. (2001). Random Forests. \emph{Machine Learning},
\emph{45}(1), 5--32. \url{https://doi.org/10.1023/A:1010933404324}

\leavevmode\vadjust pre{\hypertarget{ref-buxfcrkner2018}{}}%
Bürkner, P.-C. (2018). Advanced Bayesian Multilevel Modeling with the R
Package brms. \emph{The R Journal}, \emph{10}(1), 395.
\url{https://doi.org/10.32614/RJ-2018-017}

\leavevmode\vadjust pre{\hypertarget{ref-vanbuuren2018}{}}%
Buuren, S. van. (2018). \emph{Flexible imputation of missing data} (2nd
ed.). Chapman; Hall/CRC. \url{https://stefvanbuuren.name/fimd/}

\leavevmode\vadjust pre{\hypertarget{ref-buuren2010mice}{}}%
Buuren, S. van, \& Groothuis-Oudshoorn, K. (2010). Mice: Multivariate
imputation by chained equations in r. \emph{Journal of Statistical
Software}, 168.

\leavevmode\vadjust pre{\hypertarget{ref-craggStatisticalModelsLimited1971}{}}%
Cragg, J. G. (1971). Some {Statistical Models} for {Limited Dependent
Variables} with {Application} to the {Demand} for {Durable Goods}.
\emph{Econometrica}, \emph{39}(5), 829--844.
\url{https://doi.org/10.2307/1909582}

\leavevmode\vadjust pre{\hypertarget{ref-grahamHowManyImputations2007}{}}%
Graham, J. W., Olchowski, A. E., \& Gilreath, T. D. (2007). How {Many
Imputations} are {Really Needed}? {Some Practical Clarifications} of
{Multiple Imputation Theory}. \emph{Prevention Science}, \emph{8}(3),
206--213. \url{https://doi.org/10.1007/s11121-007-0070-9}

\leavevmode\vadjust pre{\hypertarget{ref-hesterConditionalRaceDisparities2017}{}}%
Hester, R., \& Hartman, T. K. (2017). Conditional {Race Disparities} in
{Criminal Sentencing}: {A Test} of the {Liberation Hypothesis From} a
{Non-Guidelines State}. \emph{Journal of Quantitative Criminology},
\emph{33}(1), 77--100. \url{https://doi.org/10.1007/s10940-016-9283-z}

\leavevmode\vadjust pre{\hypertarget{ref-mullahySpecificationTestingModified1986}{}}%
Mullahy, J. (1986). Specification and testing of some modified count
data models. \emph{Journal of Econometrics}, \emph{33}(3), 341--365.
\url{https://doi.org/10.1016/0304-4076(86)90002-3}

\leavevmode\vadjust pre{\hypertarget{ref-raghunathanMultivariateTechniqueMultiply2001}{}}%
Raghunathan, T. E., Lepkowski, J. M., Hoewyk, J. V., \& Solenberger, P.
(2001). A {Multivariate Technique} for {Multiply Imputing Missing Values
Using} a {Sequence} of {Regression Models}. \emph{Statistics Canada},
\emph{27}(1), 85--95.

\leavevmode\vadjust pre{\hypertarget{ref-rubinMultipleImputationNonresponse1987}{}}%
Rubin, D. B. (1987). \emph{{Multiple Imputation for Nonresponse in
Surveys {\textbar} Wiley Series in Probability and Statistics}}.
{Wiley}.

\leavevmode\vadjust pre{\hypertarget{ref-rydbergPunishingWickedExamining2018}{}}%
Rydberg, J., Cassidy, M., \& Socia, K. M. (2018). Punishing the
{Wicked}: {Examining} the {Correlates} of {Sentence Severity} for
{Convicted Sex Offenders}. \emph{Journal of Quantitative Criminology},
\emph{34}(4), 943--970. \url{https://doi.org/10.1007/s10940-017-9360-y}

\leavevmode\vadjust pre{\hypertarget{ref-stockton2023}{}}%
Stockton, B., Strange, C. C., \& Harel, O. (2023). Now You See It, Now
You Don{'}t: A Simulation and Illustration of the Importance of Treating
Incomplete Data in Estimating Race Effects in Sentencing. \emph{Journal
of Quantitative Criminology}.
\url{https://doi.org/10.1007/s10940-023-09577-w}

\leavevmode\vadjust pre{\hypertarget{ref-thompsonContextualInfluencesSentencing2020}{}}%
Thompson, L., Rydberg, J., Cassidy, M., \& Socia, K. M. (2020).
Contextual {Influences} on the {Sentencing} of {Individuals Convicted}
of {Sexual Crimes}. \emph{Sexual Abuse}, \emph{32}(7), 778--805.
\url{https://doi.org/10.1177/1079063219852936}

\leavevmode\vadjust pre{\hypertarget{ref-wooldridgeEconometricAnalysisCross2010}{}}%
Wooldridge, J. M. (2010). \emph{Econometric {Analysis} of {Cross
Section} and {Panel Data}, second edition}. {MIT Press}.

\leavevmode\vadjust pre{\hypertarget{ref-wrightRangerFastImplementation2017}{}}%
Wright, M. N., \& Ziegler, A. (2017). Ranger: {A Fast Implementation} of
{Random Forests} for {High Dimensional Data} in {C}++ and {R}.
\emph{Journal of Statistical Software}, \emph{77}, 1--17.
\url{https://doi.org/10.18637/jss.v077.i01}

\end{CSLReferences}

\newpage

\hypertarget{appendix}{%
\subsection*{Appendix}\label{appendix}}
\addcontentsline{toc}{subsection}{Appendix}

\begin{figure}

{\centering \includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-incar-cime-1.pdf}

}

\caption{\label{fig-incar-cime}Incarceration decision by most serious
crime type. 1 indicates incarceration. 0 indicates parole.}

\end{figure}

\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-sen-len-qq-1.pdf}

}

}

\subcaption{\label{fig-sen-len-qq-1}Sentence length in days}
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-sen-len-qq-2.pdf}

}

}

\subcaption{\label{fig-sen-len-qq-2}Log of sentence length plus one day}
\end{minipage}%

\caption{\label{fig-sen-len-qq}QQ plots of the sentence length (days)}

\end{figure}

\hypertarget{tbl-brms-hurdle-model-summary-2}{}
\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tbl-brms-hurdle-model-summary-2}Fixed/population-level
effects for the non-zero part of the lognormal hurdle
model.}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept & 3.87 & 0.03 & 3.82 & 3.92 \\
Age & 0.04 & 0.00 & 0.04 & 0.05 \\
Age\(^2\) & -0.02 & 0.00 & -0.03 & -0.02 \\
Sex: Male & 0.16 & 0.01 & 0.15 & 0.17 \\
Race: Black & -0.09 & 0.01 & -0.12 & -0.07 \\
Race: Latino & 0.03 & 0.05 & -0.07 & 0.13 \\
Race: Other & 0.15 & 0.06 & 0.03 & 0.27 \\
OGS & 1.28 & 0.00 & 1.27 & 1.29 \\
OGS\(^2\) & -0.13 & 0.00 & -0.13 & -0.13 \\
Prev. Rec.: 1D2D3 & 0.36 & 0.00 & 0.35 & 0.37 \\
Prev. Rec.: 4D5 & 0.86 & 0.01 & 0.85 & 0.87 \\
Prev. Rec.: REVOCDRFEL & 1.30 & 0.01 & 1.28 & 1.32 \\
Rec. Minimum & 0.20 & 0.01 & 0.18 & 0.21 \\
Crime: DUI & -0.98 & 0.01 & -1.00 & -0.97 \\
Crime: Other & 0.00 & 0.01 & -0.01 & 0.02 \\
Crime: Persons & 0.15 & 0.01 & 0.14 & 0.16 \\
Crime: Property & 0.14 & 0.01 & 0.13 & 0.15 \\
Trial & 0.47 & 0.01 & 0.45 & 0.49 \\
Male \& Black & 0.07 & 0.01 & 0.05 & 0.09 \\
Male \& Latino & 0.13 & 0.05 & 0.03 & 0.23 \\
Male \& Other & -0.12 & 0.06 & -0.24 & 0.00 \\
OGS:PRVREC1D2D3 & -0.02 & 0.00 & -0.02 & -0.01 \\
OGS:PRVREC4D5 & -0.06 & 0.00 & -0.07 & -0.05 \\
OGS:PRVRECREVOCDRFEL & -0.14 & 0.01 & -0.15 & -0.12 \\
\end{longtable}

\hypertarget{tbl-brms-hurdle-model-summary-2-zero}{}
\begin{longtable}[]{@{}lrrrr@{}}
\caption{\label{tbl-brms-hurdle-model-summary-2-zero}Fixed/population-level
effects for the zero part of the lognormal hurdle model.}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE & LB 95\% CI & UB 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept & 1.73 & 0.08 & 1.57 & 1.88 \\
Age & 0.13 & 0.00 & 0.13 & 0.14 \\
Age\(^2\) & 0.02 & 0.00 & 0.02 & 0.03 \\
Sex: Male & -0.32 & 0.01 & -0.33 & -0.31 \\
Race: Black & 0.03 & 0.01 & 0.01 & 0.06 \\
Race: Latino & -0.29 & 0.08 & -0.44 & -0.13 \\
Race: Other & -0.07 & 0.08 & -0.23 & 0.09 \\
Rec. Minimum & -0.89 & 0.01 & -0.91 & -0.87 \\
OGS & -0.41 & 0.00 & -0.42 & -0.40 \\
OGS\(^2\) & -0.22 & 0.00 & -0.23 & -0.21 \\
Prev. Rec.: 1D2D3 & -0.51 & 0.01 & -0.52 & -0.50 \\
Prev. Rec.: 4D5 & -1.11 & 0.01 & -1.13 & -1.09 \\
Prev. Rec.: REVOCDRFEL & -1.47 & 0.02 & -1.51 & -1.43 \\
Crime: DUI & -1.68 & 0.01 & -1.69 & -1.66 \\
Crime: Other & -0.30 & 0.01 & -0.32 & -0.28 \\
Crime: Persons & -0.81 & 0.01 & -0.83 & -0.79 \\
Crime: Property & -0.48 & 0.01 & -0.49 & -0.46 \\
Trial & -0.80 & 0.02 & -0.85 & -0.76 \\
Male \& Black & -0.31 & 0.02 & -0.34 & -0.28 \\
Male \& Latino & -0.39 & 0.08 & -0.56 & -0.22 \\
Male \& Other & -0.08 & 0.09 & -0.26 & 0.09 \\
\end{longtable}

\begin{figure}

\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-1.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-1}Age}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-2.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-2}Age Squared}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-3.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-3}Sex}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-4.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-4}Offender Race}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-5.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-5}OGS}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-6.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-6}OGS Squared}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-7.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-7}Prev. Rec.}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-8.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-8}Rec. Min.}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-9.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-9}Crime Type}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-10.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-10}Trial}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-11.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-11}Race by Sex}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-nonzero-12.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-nonzero-12}OGS by Prev. Rec.}
\end{minipage}%

\caption{\label{fig-cond-eff-brm2-nonzero}Posterior estimates of the
conditional effects for the non-zero-part of the lognormal hurdle
model.}

\end{figure}

\begin{figure}

\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-1.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-1}Age}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-2.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-2}Age Squared}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-3.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-3}Sex}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-4.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-4}Offender Race}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-5.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-5}OGS}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-6.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-6}OGS Squared}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-7.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-7}Prev. Rec.}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-8.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-8}Rec. Min.}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-9.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-9}Crime Type}
\end{minipage}%
\newline
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-10.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-10}Trial}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-11.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-11}Race by Sex}
\end{minipage}%
%
\begin{minipage}[t]{0.33\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{pattern-mixture-modeling_files/figure-pdf/fig-cond-eff-brm2-12.pdf}

}

}

\subcaption{\label{fig-cond-eff-brm2-12}OGS by Prev. Rec.}
\end{minipage}%

\caption{\label{fig-cond-eff-brm2}Posterior estimates of the conditional
effects for the logistic regression on the zero-part of the lognormal
hurdle model.}

\end{figure}



\end{document}
